theme: jekyll-theme-cayman
title: Stoma Automatic Detector
description: Deep Transfer Learning-Based Multi-object Detection of Plant Stomata Phenotypic Traits and Intelligent Recognition System. <br> 基于深度迁移学习的植物气孔表型性状的高通量多目标检测与智能识别系统
